### ISSUE TITLE
OSF API replies Not Found error for contents of folders

### ISSUE THREAD

**Issue by dschreij** [CenterForOpenScience/waterbutler#209]
Recently the OSF API started to reply with an error message when a folder is queried for its contents. In our file tree, the folder itself shows but is empty.
Below is a screenshot of a specific error message that occurred for @smathot :
![0](https://cloud.githubusercontent.com/assets/689044/24773821/a50b5594-1ae4-11e7-924b-6df4957e62f4.png)
This happens for *all* folders of *all* storage providers and projects. We are certain the folders exist and are not empty.

**Comment by dschreij** [comment]
We only work with links from the API

**Comment by felliott** [comment]
What's the id of the project you're fetching files for?

**Comment by felliott** [comment]
@dschreij, that might have been fixed by a hotfix release yesterday.  Do you mind trying it again?  The url it should be following should have the 5-letter project id between `/nodes/` and `/files/`.

**Comment by dschreij** [comment]
It is for all the projects. The above one is just an example (and I don't know which project in specific @smathot received the above error for) Our program starts by requesting all projects of a user (which goes correctly), and then traverses the links that the API provides (in the files entry), to compose a file tree. This work until folders are encountered.

**Comment by dschreij** [comment]
I just checked it, and the problem appears to be gone! Great work!
The only thing I do still get is an error message from Github about a 'Bad Gateway', but we had already filed another issue for that:

![screenshot 2017-04-07 15 52 14](https://cloud.githubusercontent.com/assets/689044/24817366/38d0814e-1baa-11e7-803c-97b6f6edeb69.png)

Regardless, I think this issue can be closed.

**Comment by smathot** [comment]
Excellent, guys! It works again.

**Comment by felliott** [comment]
📯 🎉
